
export const SKILLS = [
    { label: "ITES", value : "ITES"},
    { label: "Marketing", value : "Marketing"},
    { label: "IT Software - Application Programming", value : "IT Software - Application Programming"},
    { label: "Production", value : "Production"},
    { label: "Executive Assistant", value : "Executive Assistant"},
    { label: "IT Software - Other", value : "IT Software - Other"},
    { label: "Engineering Design", value : "Engineering Design"},
    { label: "Sales", value : "Sales"},
    { label: "Supply Chain", value : "Supply Chain"},
    { label: "Site Engineering", value : "Site Engineering"},
    { label: "Defence Forces", value : "Defence Forces"},
    { label: "HR", value : "HR"},
    { label: "Hotels", value : "Hotels"},
    { label: "IT Software - Network Administration", value : "IT Software - Network Administration"},
    { label: "Teaching", value : "Teaching"},
    { label: "Accounts", value : "Accounts"},
    { label: "Medical", value : "Medical"},
    { label: "Design", value : "Design"},
    { label: "IT Software - System Programming", value : "IT Software - System Programming"},
    { label: "IT Software - eCommerce", value : "IT Software - eCommerce"},
    { label: "Financial Services", value : "Financial Services"},
    { label: "IT Software - Client/Server Programming", value : "IT Software - Client/Server Programming"},
    { label: "IT Software - ERP", value : "IT Software - ERP"},
    { label: "IT Hardware", value : "IT Hardware"},
    { label: "Analytics & Business Intelligence", value : "Analytics & Business Intelligence"},
    { label: "IT Software - Telecom Software", value : "IT Software - Telecom Software"},
    { label: "IT Software - DBA", value : "IT Software - DBA"},
    { label: "IT Software - Mobile", value : "IT Software - Mobile"},
    { label: "TV", value : "TV"},
    { label: "Architecture", value : "Architecture"},
    { label: "IT Software - Mainframe", value : "IT Software - Mainframe"},
    { label: "Journalism", value : "Journalism"},
    { label: "Top Management", value : "Top Management"},
    { label: "IT Software - QA & Testing", value : "IT Software - QA & Testing"},
    { label: "Strategy", value : "Strategy"},
    { label: "Travel", value : "Travel"},
    { label: "Export", value : "Export"},
    { label: "IT Software - Embedded", value : "IT Software - Embedded"},
    { label: "Packaging", value : "Packaging"},
    { label: "Fashion Designing", value : "Fashion Designing"},
    { label: "IT Software - Middleware", value : "IT Software - Middleware"},
    { label: "Legal", value : "Legal"},
    { label: "IT Software - Systems", value : "IT Software - Systems"},
    { label: "Shipping", value : "Shipping"},
    { label: "Beauty/Fitness/Spa Services", value : "Beauty/Fitness/Spa Services"}
];